# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
#pipeline => Stages => job => steps (task)
stages:
- stage: Build
  jobs: 
  - job: FirstJob
    steps:
      - script: echo FirstJob

- stage: DevDeploy
  dependsOn:
  - Build
  jobs: 
    - job: FirstJobfromDevDeploy
      steps:
        - script: echo FirstJobfromDevDeploy

- stage: QaDeploy
  dependsOn:
  - build
  - DevDeploy
  jobs:
    - job: FirstjobforQADeploy
      steps:
        - script: echo FirstjobforQADeploy

- stage: ProdDeploy
  dependsOn:
  - Build
  - DevDeploy
  - QaDeploy
  jobs:
    - job: FirstJObforProd
      steps:
        - script: echo firstfromprod

  